routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\KoranController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes --
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\User\HomeController::class, 'index'])->name('home');
Route::get('/ruang', [App\Http\Controllers\User\HomeController::class, 'ruang'])->name('ruang');

// Route::get('/home', [App\Http\Controllers\User\HomeController::class, 'index'])->name('home');
Route::group(['prefix' => '/tentang-kami'], function () {
    Route::get('/sambutan', [App\Http\Controllers\User\TentangController::class, 'sambutan'])->name('tentang-kami.sambutan');
    Route::get('/visi-misi', [App\Http\Controllers\User\TentangController::class, 'visiMisi'])->name('tentang-kami.visiMisi');
    Route::get('/tugas-dan-fungsi', [App\Http\Controllers\User\TentangController::class, 'tugasFungsi'])->name('tentang-kami.tugasFungsi');
    Route::get('/rencana-strategis', [App\Http\Controllers\User\TentangController::class, 'rencanaStrategis'])->name('tentang-kami.rencanaStrategis');
    Route::get('/profil-biro-rpm', [App\Http\Controllers\User\TentangController::class, 'profilBiro'])->name('tentang-kami.profilBiro');
});
Route::get('/lppm', [App\Http\Controllers\User\LppmController::class, 'index'])->name('lppm');
Route::get('/direktorat-inovasi', [App\Http\Controllers\User\DirektoratInovasiController::class, 'index'])->name('direktorat');
Route::get('/bbrpm', [App\Http\Controllers\User\BbrpmController::class, 'index'])->name('bbrpm');
Route::get('/informasi', [App\Http\Controllers\User\InformasiController::class, 'index'])->name('informasi');
Route::get('/dokumentasi', [App\Http\Controllers\User\DokumentasiController::class, 'index'])->name('dokumentasi');
Route::get('/pui', [App\Http\Controllers\User\PuiController::class, 'index'])->name('pui');

Route::get('/login', [App\Http\Controllers\Auth\LoginController::class, 'index'])->name('login');
Route::post('/login', [App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login.post');
Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::get('/coming', function () {
    return view('user.coming');
})->name('coming');

Route::get('/admin_pusat_list_dosen_aktif', function () {
    return view('/admin_pusat/ap_dosen_aktif/dosen_aktif_list');
})->name('admin_pusat_list_dosen_aktif');

Route::group(['prefix' => '/mahasiswa-kkn'], function () {
    Route::get('/detail-mahasiswa-kkn', [App\Http\Controllers\User\MahasiswaKKNController::class, 'detail'])->name('mahasiswa-kkn.detail');
    Route::get('/', [App\Http\Controllers\User\MahasiswaKKNController::class, 'index'])->name('mahasiswa-kkn.index');
});

Route::get('/slider', [App\Http\Controllers\SliderController::class, 'index']);
Route::get('/slider/create', [App\Http\Controllers\SliderController::class, 'create']);
Route::post('/slider/upload', [App\Http\Controllers\SliderController::class, 'store']);
Route::post('/slider/view', [App\Http\Controllers\SliderController::class, 'view']);

Route::middleware(['auth:sanctum', 'RoleAuth'])->group(function () {
    Route::get('/dokumentasi-rida', [App\Http\Controllers\User\RidaController::class, 'index'])->name('dokumentasi-rida');
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        Route::group(['as' => 'menu.', 'prefix' => '/menu'], function () {
            Route::get('/', [App\Http\Controllers\Menu\MenuController::class, 'index'])->name('index');
            Route::get('/create', [App\Http\Controllers\Menu\MenuController::class, 'add'])->name('add');
            Route::post('/create', [App\Http\Controllers\Menu\MenuController::class, 'create'])->name('create');
            Route::get('/edit/{id}', [App\Http\Controllers\Menu\MenuController::class, 'edit'])->name('edit');
            Route::post('/edit/{id}', [App\Http\Controllers\Menu\MenuController::class, 'update'])->name('update');
            Route::get('/delete/{id}', [App\Http\Controllers\Menu\MenuController::class, 'delete'])->name('delete');
        });

        Route::group(['as' => 'capaian_iku.', 'prefix' => '/capaian_iku'], function () {
            Route::get('/', [App\Http\Controllers\Rida\IkuController::class, 'index'])->name('index');
            Route::get('/pilihperiode/{target_capaian}', [App\Http\Controllers\Rida\IkuController::class, 'pilihperiode'])->name('pilihperiode');
            Route::get('/details/{target_capaian}/{periode}/{tahun_input}', [App\Http\Controllers\Rida\IkuController::class, 'details'])->name('details');
            Route::get('/create', [App\Http\Controllers\Rida\IkuController::class, 'add'])->name('add');
            Route::post('/create', [App\Http\Controllers\Rida\IkuController::class, 'create'])->name('create');
            Route::get('/edit/{id}', [App\Http\Controllers\Rida\IkuController::class, 'edit'])->name('edit');
            Route::post('/edit/{target}/{periode}/{tahun_input}/{sumber_data}', [App\Http\Controllers\Rida\IkuController::class, 'update'])->name('update');
            Route::get('/delete/{nama_fakultas}/{periode}/{tahun_input}', [App\Http\Controllers\Rida\IkuController::class, 'delete'])->name('delete');
            Route::get('/export', [App\Http\Controllers\Rida\IkuController::class, 'export'])->name('export');
            Route::post('/import', [App\Http\Controllers\Rida\IkuController::class, 'import'])->name('import');
        });

        Route::group(['as' => 'hibahpnbp.', 'prefix' => '/hibahpnbp'], function () {
            Route::get('/', [App\Http\Controllers\Rida\HibahPNBPController::class, 'index'])->name('index');
            Route::get('/pilihperiode/{target_capaian}', [App\Http\Controllers\Rida\HibahPNBPController::class, 'pilihperiode'])->name('pilihperiode');
            Route::get('/details/{periode}/{tahun_input}', [App\Http\Controllers\Rida\HibahPNBPController::class, 'details'])->name('details');
            Route::get('/create', [App\Http\Controllers\Rida\HibahPNBPController::class, 'add'])->name('add');
            Route::post('/create', [App\Http\Controllers\Rida\HibahPNBPController::class, 'create'])->name('create');
            Route::get('/edit/{id}', [App\Http\Controllers\Rida\HibahPNBPController::class, 'edit'])->name('edit');
            Route::post('/edit/{periode}/{tahun_input}/{sumber_data}', [App\Http\Controllers\Rida\HibahPNBPController::class, 'update'])->name('update');
            Route::get('/delete/{periode}/{tahun_input}', [App\Http\Controllers\Rida\HibahPNBPController::class, 'delete'])->name('delete');
            Route::get('/export', [App\Http\Controllers\Rida\HibahPNBPController::class, 'export'])->name('export');
            Route::post('/import', [App\Http\Controllers\Rida\HibahPNBPController::class, 'import'])->name('import');
            Route::post('/update/nama/table/{nama_table}', [App\Http\Controllers\Rida\HibahPNBPController::class, 'updateNamaTable'])->name('updateNamaTable');
        });

        Route::group(['as' => 'skemapnbp.', 'prefix' => '/skemapnbp'], function () {
            Route::get('/', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'index'])->name('index');

            Route::get('/pilihperiode/{target_capaian}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'pilihperiode'])->name('pilihperiode');
            Route::get('/details/{periode}/{tahun_input}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'details'])->name('details');
            Route::get('/details/{skema}/{periode}/{tahun_input}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'detailsSkema'])->name('details-skema');
            Route::get('/details-5tahun/', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'detailsSkema5Tahun'])->name('details-5tahun');
            Route::get('/details-5tahun/jenisSkema/{skema}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'detailsSkemaFakultas5Tahun'])->name('details-skemaFakultas5tahun');
            Route::get('/details-5tahun/jenisSkema/{skema}/', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'detailsSkemaFakultas5Tahun'])->name('details-skemaFakultas5tahun');

            Route::get('/create', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'add'])->name('add');
            Route::post('/create', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'create'])->name('create');
            Route::get('/edit/{id}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'edit'])->name('edit');
            Route::post('/edit/{target}/{periode}/{tahun_input}/{sumber_data}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'update'])->name('update');
            Route::get('/delete/{nama_fakultas}/{periode}/{tahun_input}', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'delete'])->name('delete');
            Route::get('/export', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'export'])->name('export');
            Route::post('/import', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'import'])->name('import');
            Route::post('/editPeriode', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'editPeriode'])->name('edit-periode');
            Route::post('/editJumlah', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'editJumlah'])->name('edit-jumlah');
            Route::post('/deletePeriode', [App\Http\Controllers\Rida\SkemaPNBPController::class, 'deletePeriode'])->name('delete-periode');

resources/views/admin/capaian_iku/details.blade.php
@extends('layout.application')

@section('css')
    <link href="{{ asset('js/plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/plugins/data-tables/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/data-tables/data-tables-script.js') }}"></script>
@endsection


@section('content')
    @include('layout.navbar')
    <!-- START MAIN -->
        <div id="main">
    <!-- START WRAPPER -->
        <div class="wrapper">
    @include('layout.menu')
	<!-- START CONTENT -->
           <!-- START CONTENT -->
    <section id="content">
      <!--breadcrumbs start-->
      <div id="breadcrumbs-wrapper">
          <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
        <div class="container">
          <!-- <div class="row">
            <div class="col s12 m12 l12">
              <h5 class="breadcrumbs-title">agenda</h5>
              <ol class="breadcrumbs">
                  <li><a href="index.htm">Dashboard</a></li>
                  <li><a href="#">Tables</a></li>
                  <li class="active">Basic Tables</li>
              </ol>
            </div>
          </div> -->
        </div>
      </div>
      <!--breadcrumbs end-->
      <!--start container-->
      <div class="container">
        <div class="section">    
          <!--DataTables example-->
          @if (session('message'))
          <div style="background-color: #aee8e2; border-radius:10px; padding:10px; margin-bottom:10px;">
            <b>{{ session('message') }}</b>
          </div>
          @endif

          <div id="table-datatables">
          
            <h4 class="header left">Tabel 1 Perkembangan Capaian IKU Universitas Sebelas Maret</h4>
            <!-- <a href="{{route('admin.agenda.create')}}" class="waves-effect waves-light btn-large right"><i class="mdi-content-add left"></i>Tambah Agenda</a> -->
            <div class="row">
              <div class="col s12 m12 l12">
              
                <table id="data-menu" class="table display" cellspacing="0">
                  <thead>
                      <tr>
                          <th style="text-align:justify !important;">No</th>
                          <th style="text-align:justify !important;">Detail Target</th>
                          <th style="text-align:justify !important;">Satuan</th>
                          <th style="text-align:justify !important;">Target</th>
                          <th style="text-align:justify !important;">Capaian</th>
                          <th style="text-align:justify !important;">%</th>
                          <th style="text-align:justify !important;">Action</th>
                      </tr>
                  </thead>
                  <tbody>
                  @php
                      $i = 1;
                    @endphp
                      @foreach ($iku as $row)
                      <tr>
                          <td style="text-align:center !important;">{{$row->no}}</td>
                          <td style="text-align:center !important;">{{$row->detail_target}}</td>
                          <td style="text-align:center !important;">{{$row->satuan}}</td>
                          <td style="text-align:center !important;">{{$row->target}}</td>
                          <td style="text-align:center !important;">{{$row->capaian}}</td>
                          <td style="text-align:center !important;">{{$row->percenttotal}}%</td>
                          
                          <td><a href="#" class="btn modal-trigger" style="background-color: orange;">Edit</a>   </td>
                          <!-- Modal Edit -->
                          <div id="#" class="modal modal-fixed-footer">
                            <form action="#" method="post">
                              @csrf
                              <div class="modal-content">
                                <h4>Edit Data</h4>
                                <hr>
                                <div class="row">
                                  <div class="input-field col s12">
                                    <input value="{{$row->title}}" id="title" name="title"  type="text" class="validate" required>
                                    <label for="title">RIDA title</label>
                                  </div>
                                </div>
                                
                                <div class="row">
                                  <div class="mb-3" style="margin-left:8px">
                                    <label for="date">Rida date</label>
                                    <input value="{{$row->date}}" id="date"  name="date"  type="date" class="validate" required>
                                  </div>
                                </div>
                                
                                <div class="row">
                                  <div class="mb-3" style="margin-left:8px">
                                    <label for="time">Rida time</label>
                                    <input value="{{$row->time}}" id="time"  name="time"  type="time" class="validate" required>
                                  </div>
                                </div>
                                
                                
                                
                              </div>
                              <div class="modal-footer">
                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                                <button type="submit" class="modal-close waves-effect waves-green btn-flat">Update</button>
                              </div>
                            </form>
                          </div>
                          <!-- Modal Hapus -->
                          <div id="hapus" class="modal">
                            <form action="#" method="get">
                              @csrf
                              <div class="modal-content">
                                <h4>Delete Data IKU</h4>
                                <hr>
                                <p>Anda yakin ingin menghapus data {{$row->title}}?</p>
                                <div class="modal-footer">
                                  <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                                  <button type="submit" class="modal-close waves-effect waves-green btn-flat">Delete</button>
                                </div>
                              </form>
                            </div>
                          </tr>
                          @php
                          $i++;
                          @endphp
                          @endforeach
                          
                          
                        </tbody>
                </table>
              </div>
            </div>
          </div> 
          <br>
          <div class="divider"></div> 
          <!--DataTables example Row grouping-->
        </div>
      </div>
      <!--end container-->

    </section>
    <!-- END CONTENT -->
            @if (session('message'))
            <div style="background-color: #aee8e2; border-radius:10px; padding:10px; margin-bottom:10px;">
                <b>{{ session('message') }}</b>
            </div>
            @endif
            
                            
<!-- END CONTENT -->
@endsection

resources/views/admin/capaian_iku/index.blade.php
@extends('layout.application')

@section('css')
    <link href="{{ asset('js/plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/plugins/data-tables/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/data-tables/data-tables-script.js') }}"></script>
@endsection


@section('content')
    @include('layout.navbar')
    <!-- START MAIN -->
        <div id="main">
    <!-- START WRAPPER -->
        <div class="wrapper">
    @include('layout.menu')
	<!-- START CONTENT -->
           <!-- START CONTENT -->
    <section id="content">
      <!--breadcrumbs start-->
      <div id="breadcrumbs-wrapper">
          <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
        <div class="container">
          <!-- <div class="row">
            <div class="col s12 m12 l12">
              <h5 class="breadcrumbs-title">agenda</h5>
              <ol class="breadcrumbs">
                  <li><a href="index.htm">Dashboard</a></li>
                  <li><a href="#">Tables</a></li>
                  <li class="active">Basic Tables</li>
              </ol>
            </div>
          </div> -->
        </div>
      </div>
      <!--breadcrumbs end-->
      <!--start container-->
      <div class="container">
        <div class="section">    
          <!--DataTables example-->
          @if (session('message'))
          <div style="background-color: #aee8e2; border-radius:10px; padding:10px; margin-bottom:10px;">
            <b>{{ session('message') }}</b>
          </div>
          @endif

          <div id="table-datatables">
            <h4 class="header left">Tabel 1 Perkembangan Capaian IKU Universitas Sebelas Maret</h4>
            <!-- <a href="{{route('admin.agenda.create')}}" class="waves-effect waves-light btn-large right"><i class="mdi-content-add left"></i>Tambah Agenda</a> -->
            <div class="row">
              <div class="col s12 m12 l12">
                <a href="#import" class="waves-effect waves-light btn right modal-trigger" role="button">Upload Excel</a>
                <!-- <a href="{{route('admin.capaian_iku.export')}}" class="waves-effect waves-light btn right" role="button">Export Excel</a> -->

                {{-- Modal import --}}
                <div id="import" class="modal">
                  <form action="{{route('admin.capaian_iku.import')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-content">
                      <h4>Import Data</h4>
                      <p>Untuk import data melalui excel, silahkan download template excel berikut dan sesuaikan data anda</p>
                      <a href="{{asset('template\rida\table_1_capaian_iku.xlsx')}}">Download template</a>
                        <h5><label for="iku" class="form-label">Upload file excel</label></h5>
                        <input type="file" name="iku">

                        <h5><label for="tahun" class="form-label">Tahun</label></h5>
                        <input type="text" name="tahun">
                        
                        <h5><label for="periode" class="form-label">Periode</label></h5>
                        <input type="text" name="periode">

                        <h5><label for="sumber_data" class="form-label">Sumber Data</label></h5>
                        <input type="text" name="sumber_data">
                    </div>
                   
                    <div class="modal-footer">
                      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                      <button type="submit" class="waves-effect waves-green btn">Submit</button>
                    </div>
                  </form>
                </div>
                {{-- End of modal import --}}

                <table id="data-menu" class="table display" cellspacing="0">
                  <thead>
                      <tr>
                          <th>#</th>
                          <th>IK</th>
                          <th>Target</th>
                          <th>Action</th>
                      </tr>
                  </thead>
                  <tbody>
                    @php
                      $i = 1;
                    @endphp
                      @foreach ($iku as $row)
                      <tr>
                          <td>{{$i}}</td>
                          <td>{{$row->ik}}</td>
                          <td>{{$row->target_capaian}}</td>
                         
                          <td><a href="{{route('admin.capaian_iku.pilihperiode' , $row->target_capaian )}}" class="btn" style="background-color: grey;">Detail</a></td>
                      </tr>
                      @php
                        $i++;
                      @endphp
                      @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div> 
          <br>
          <div class="divider"></div> 
          <!--DataTables example Row grouping-->
        </div>
      </div>
      <!--end container-->

    </section>
    <!-- END CONTENT -->
            @if (session('message'))
            <div style="background-color: #aee8e2; border-radius:10px; padding:10px; margin-bottom:10px;">
                <b>{{ session('message') }}</b>
            </div>
            @endif
            
                            
<!-- END CONTENT -->
@endsection

resources/views/admin/capaian_iku/pilihperiode.blade.php
@extends('layout.application')

@section('css')
    <link href="{{ asset('js/plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
@endsection

@section('js')
    <script type="text/javascript" src="{{ asset('js/plugins/data-tables/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/data-tables/data-tables-script.js') }}"></script>
@endsection


@section('content')
    @include('layout.navbar')
    <!-- START MAIN -->
        <div id="main">
    <!-- START WRAPPER -->
        <div class="wrapper">
    @include('layout.menu')
	<!-- START CONTENT -->
           <!-- START CONTENT -->
    <section id="content">
      <!--breadcrumbs start-->
      <div id="breadcrumbs-wrapper">
          <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
        </div>
        <div class="container">
          <!-- <div class="row">
            <div class="col s12 m12 l12">
              <h5 class="breadcrumbs-title">agenda</h5>
              <ol class="breadcrumbs">
                  <li><a href="index.htm">Dashboard</a></li>
                  <li><a href="#">Tables</a></li>
                  <li class="active">Basic Tables</li>
              </ol>
            </div>
          </div> -->
        </div>
      </div>
      <!--breadcrumbs end-->
      <!--start container-->
      <div class="container">
        <div class="section">    
          <!--DataTables example-->
          @if (session('message'))
          <div style="background-color: #aee8e2; border-radius:10px; padding:10px; margin-bottom:10px;">
            <b>{{ session('message') }}</b>
          </div>
          @endif

          <div id="table-datatables">
           
              <h4 class="header left">Tabel 1 Perkembangan Capaian IKU Universitas Sebelas Maret</h4>

            <div class="row">
              <div class="col s12 m12 l12">
              
                <table id="data-menu" class="table display" cellspacing="0">
                  <thead>
                      <tr>
                          <th style="text-align:justify !important;">#</th>
                          <th style="text-align:center !important;">Periode</th>
                          <th style="text-align:center !important;">Tahun</th>
                          <th style="text-align:center !important;">Sumber Data</th>
                          <th style="text-align:justify !important;">Action</th>
                      </tr>
                  </thead>
                  <tbody>
                  @php
                      $i = 1;
                    @endphp
                      @foreach ($data as $row)
                      <tr>
                          <td style="text-align:center !important;">{{$i}}</td>
                          <td style="text-align:center !important;">{{$row->periode}}</td>
                          <td style="text-align:center !important;">{{$row->tahun_input}}</td>
                          <td style="text-align:center !important;">{{$row->sumber_data}}</td>
                          <td>
                            <a href="{{route('admin.capaian_iku.details', [$target, $row->periode, $row->tahun_input]  )}}" class="btn" style="background-color: grey;">Detail</a>
                            <a href="#edit" class="btn modal-trigger" style="background-color: green;">Edit</a>
                            <a href="#hapus" class="btn modal-trigger" style="background-color: red;">Delete</a>
                          </td>
                          <!-- Modal Edit -->
                          <div id="edit" class="modal modal-fixed-footer">
                            <form action="{{route('admin.capaian_iku.update', [$target,$row->periode, $row->tahun_input, $row->sumber_data]  )}}" method="post">
                              @csrf
                              <div class="modal-content">
                                <h4>Edit Data</h4>
                                <hr>
                                <div class="row">
                                  <div class="input-field col s12">
                                    <input value="{{$row->periode}}" id="periode" name="periode"  type="text" class="validate" required>
                                    <label for="periode">Periode</label>
                                  </div>
                                </div>

                                <div class="row">
                                  <div class="mb-3" style="margin-left:8px">
                                    <label for="tahun_input">Tahun</label>
                                    <input value="{{$row->tahun_input}}" id="tahun_input"  name="tahun_input"  type="text" class="validate" required>
                                  </div>
                                </div>
                                <div class="row">
                                  <div class="mb-3" style="margin-left:8px">
                                    <label for="sumber_data">Sumber Data</label>
                                    <input value="{{$row->sumber_data}}" id="sumber_data"  name="sumber_data"  type="text" class="validate" required>
                                  </div>
                                </div>
                              </div>

                              <div class="modal-footer">
                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                                <button type="submit" class="modal-close waves-effect waves-green btn-flat">Update</button>
                              </div>
                            </form>
                          </div>
                          <!-- Modal Hapus -->
                          <div id="hapus" class="modal">
                            <form action="{{route('admin.capaian_iku.delete', [$target, $row->periode, $row->tahun_input]  )}}" method="get">
                              @csrf
                              <div class="modal-content">
                                <h4>Hapus Tabel</h4>
                                <hr>
                                <p>Anda yakin ingin menghapus Tabel {{ $row->periode }} tahun {{ $row->tahun_input }} ?</p>
                              <div class="modal-footer">
                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                                <button type="submit" class="modal-close waves-effect waves-green btn-flat">Delete</button>
                              </div>
                            </form>
                          </div>
                      </tr>
                      @php
                        $i++;
                      @endphp
                      @endforeach
                      
                  </tbody>
                  
                </table>
              </div>
            </div>
          </div> 
          <br>
          <div class="divider"></div> 
          <!--DataTables example Row grouping-->
        </div>
      </div>
      <!--end container-->

    </section>
    <!-- END CONTENT -->
            @if (session('message'))
            <div style="background-color: #aee8e2; border-radius:10px; padding:10px; margin-bottom:10px;">
                <b>{{ session('message') }}</b>
            </div>
            @endif
            
                            
<!-- END CONTENT -->
@endsection